### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rodrigoeduardo** [rodrigoeduardo/major-wordle#1]
- [ ] Pick a random player every day
- [x] Set max tries
- [ ] Make share text more cool
- [x] ~Settings modal~
- [x] Tutorial modal
- [ ] Save statistics on LocalStorage
- [ ] Blurred player photo
- [x] Set page title and favicon
- [ ] Set metatags
